var slides = {
    waterPlants: {
        waterplant1: [{
            sprite: "waterplant1",
            duration: 1000
        }, {
            sprite: "waterplant1_bloom",
            duration: 10958
        }, {
            sprite: "waterplant1_buchanka",
            duration: 11871
        }, {
            sprite: "waterplant1_stem",
            duration: 3000
        }, {
            sprite: "waterplant1_root",
            duration: 0
        }],
        waterplant2: [{
            sprite: "waterplant2",
            duration: 1000
        }, {
            sprite: "waterplant2_leafs",
            duration: 4181
        }, {
            sprite: "waterplant2_bloom",
            duration: 6354
        }, {
            sprite: "waterplant2_stem",
            duration: 6066
        }, {
            sprite: "waterplant2_fruit",
            duration: 0
        }],
        waterplant3: [{
            sprite: "waterplant3",
            duration: 1000
        }, {
            sprite: "waterplant3_leaves",
            duration: 7287
        }, {
            sprite: "waterplant3_leaf_petiole",
            duration: 8635
        }, {
            sprite: "waterplant3_bloom",
            duration: 4789
        }, {
            sprite: "waterplant3_fruit",
            duration: 3230
        }, {
            sprite: "waterplant3_root",
            duration: 6502
        }, {
            sprite: "waterplant3",
            duration: 0
        }],
        waterplant4: [{
            sprite: "waterplant4",
            duration: 11764
        }, {
            sprite: "waterplant4_leaves",
            duration: 7445
        }, {
            sprite: "waterplant4_root",
            duration: 9523
        }, {
            sprite: "waterplant4_bloom",
            duration: 6104
        }, {
            sprite: "waterplant4_fruit",
            duration: 3886
        }, {
            sprite: "waterplant4",
            duration: 0
        }],
        waterplant5: [{
            sprite: "waterplant5",
            duration: 1000
        }, {
            sprite: "waterplant5_leaves",
            duration: 5444
        }, {
            sprite: "waterplant5_bloom_fruit",
            duration: 4182
        }, {
            sprite: "waterplant5_root",
            duration: 4862
        }, {
            sprite: "waterplant5",
            duration: 0
        }]
    },
    plants: {
        plant1: [{
            sprite: "plant1",
            duration: 7105
        }, {
            sprite: "plant1_leaves",
            duration: 7367
        }, {
            sprite: "plant1_bloom",
            duration: 10916
        }, {
            sprite: "plant1_fruit",
            duration: 2313
        }, {
            sprite: "plant1_whip",
            duration: 9283
        }, {
            sprite: "plant1",
            duration: 0
        }],
        plant2: [{
            sprite: "plant2",
            duration: 6835
        }, {
            sprite: "plant2_root",
            duration: 4789
        }, {
            sprite: "plant2_stalk_leaf",
            duration: 4174
        }, {
            sprite: "plant2_bloom",
            duration: 5013
        }, {
            sprite: "plant2_fruit",
            duration: 6040
        }, {
            sprite: "plant2_reedbeeds",
            duration: 12379
        }, {
            sprite: "plant2",
            duration: 0
        }],
        plant3: [{
            sprite: "plant3",
            duration: 5703
        }, {
            sprite: "plant3_root",
            duration: 5445
        }, {
            sprite: "plant3_leaves",
            duration: 2798
        }, {
            sprite: "plant3_bloom",
            duration: 14060
        }, {
            sprite: "plant3_fruit",
            duration: 3692
        }, {
            sprite: "plant3",
            duration: 0
        }],
        plant4: [{
            sprite: "plant4",
            duration: 8475
        }, {
            sprite: "plant4_leaves",
            duration: 6484
        }, {
            sprite: "plant4_bloom",
            duration: 7794
        }, {
            sprite: "plant4_fruit",
            duration: 6289
        }, {
            sprite: "plant4",
            duration: 0
        }],
        plant5: [{
            sprite: "plant5_bloom",
            duration: 8211
        }, {
            sprite: "plant5",
            duration: 8609
        }, {
            sprite: "plant5_fruit",
            duration: 2635
        }, {
            sprite: "plant5",
            duration: 0
        }]
    },
    fishes: {
        fish1: [{
            sprite: "fish1_innature",
            duration: 10928
        }, {
            sprite: "fish1_teeth",
            duration: 17676
        }, {
            sprite: "fish1_feeding",
            duration: 19142
        }, {
            sprite: "fish1",
            duration: 0
        }],
        fish2: [{
            sprite: "fish2",
            duration: 12060
        }, {
            sprite: "fish2_innature",
            duration: 13192
        }, {
            sprite: "fish2_inpond",
            duration: 0
        }],
        fish3: [{
            sprite: "fish3_fishingpond",
            duration: 13105
        }, {
            sprite: "fish3",
            duration: 12597
        }, {
            sprite: "fish3_innature",
            duration: 16297
        }, {
            sprite: "fish3",
            duration: 0
        }],
        fish4: [{
            sprite: "fish4_innature",
            duration: 12974
        }, {
            sprite: "fish4",
            duration: 0
        }],
        fish5: [{
            sprite: "fish5_inpond",
            duration: 14846
        }, {
            sprite: "fish5",
            duration: 12307
        }, {
            sprite: "fish5_hunting",
            duration: 0
        }],
        fish6: [{
            sprite: "fish6",
            duration: 18416
        }, {
            sprite: "fish6_head",
            duration: 15340
        }, {
            sprite: "fish6_inpond",
            duration: 17270
        }, {
            sprite: "fish6_eating",
            duration: 0
        }]
    },
    birds: {
        bird1: [{
            sprite: "bird1_wingspan",
            duration: 17212
        }, {
            sprite: "bird1_inwater",
            duration: 18721
        }, {
            sprite: "bird1_innature",
            duration: 15702
        }, {
            sprite: "bird1_hunting",
            duration: 32900
        }, {
            sprite: "bird1_nesting",
            duration: 0
        }],
        bird2: [{
            sprite: "bird2_innature",
            duration: 13758
        }, {
            sprite: "bird2_nesting",
            duration: 12941
        }, {
            sprite: "bird2_innature",
            duration: 23249
        }, {
            sprite: "bird2_withbrood",
            duration: 20332
        }, {
            sprite: "bird2",
            duration: 0
        }],
        bird3: [{
            sprite: "bird3_malefemale",
            duration: 18795
        }, {
            sprite: "bird3_flock",
            duration: 13405
        }, {
            sprite: "bird3_inwater",
            duration: 16562
        }, {
            sprite: "bird3_feeding",
            duration: 0
        }],
        bird4: [{
            sprite: "bird4",
            duration: 18750
        }, {
            sprite: "bird4_pair",
            duration: 15688
        }, {
            sprite: "bird4_feeding",
            duration: 19345
        }, {
            sprite: "bird4_peoplefeeding",
            duration: 12655
        }, {
            sprite: "bird4_nest",
            duration: 13177
        }, {
            sprite: "bird4_brood",
            duration: 0
        }],
        bird5: [{
            sprite: "bird5_feet",
            duration: 12495
        }, {
            sprite: "bird5",
            duration: 30796
        }, {
            sprite: "bird5_ontree",
            duration: 11784
        }, {
            sprite: "bird5_feeding",
            duration: 16820
        }, {
            sprite: "bird5_ontree",
            duration: 12916
        }, {
            sprite: "bird5_diving",
            duration: 0
        }]
    },
    amphs: {
        amph1: [{
            sprite: "amph1_nature",
            duration: 51432
        }, {
            sprite: "amph1",
            duration: 0
        }],
        amph2: [{
            sprite: "amph2_eggs",
            duration: 21249
        }, {
            sprite: "amph2",
            duration: 24314
        }, {
            sprite: "amph2_nature",
            duration: 0
        }],
        amph3: [{
            sprite: "amph3_tree",
            duration: 17177
        }, {
            sprite: "amph3_stick",
            duration: 5921
        }, {
            sprite: "amph3_leg",
            duration: 5378
        }, {
            sprite: "amph3_throat",
            duration: 24158
        }, {
            sprite: "amph3_leaf",
            duration: 0
        }],
        amph4: [{
            sprite: "amph4",
            duration: 7718
        }, {
            sprite: "amph4_legs",
            duration: 10158
        }, {
            sprite: "amph4_nature",
            duration: 19833
        }, {
            sprite: "amph4_eggs",
            duration: 4099
        }, {
            sprite: "amph4_tadpole_wolegs",
            duration: 6728
        }, {
            sprite: "amph4_tadpole_wlegs",
            duration: 0
        }],
        amph5: [{
            sprite: "amph5",
            duration: 12928
        }, {
            sprite: "amph5_eggs",
            duration: 11009
        }, {
            sprite: "amph5_nature",
            duration: 0
        }],
        amph6: [{
            sprite: "amph6",
            duration: 14158
        }, {
            sprite: "amph6_head",
            duration: 10124
        }, {
            sprite: "amph6_nature",
            duration: 14304
        }, {
            sprite: "amph6_skin",
            duration: 6275
        }, {
            sprite: "amph6_eggs",
            duration: 19316
        }, {
            sprite: "amph6_baby",
            duration: 6844
        }, {
            sprite: "amph6_nature",
            duration: 0
        }],
        amph7: [{
            sprite: "amph7",
            duration: 10231
        }, {
            sprite: "amph7_underwater",
            duration: 1111
        }, {
            sprite: "amph7_eggs",
            duration: 13090
        }, {
            sprite: "amph7_larva",
            duration: 753
        }, {
            sprite: "amph7",
            duration: 0
        }]
    },
    insects: {
        insect1: [{
            sprite: "insect1",
            duration: 18326
        }, {
            sprite: "insect1_female_male",
            duration: 3652
        }, {
            sprite: "insect1",
            duration: 18808
        }, {
            sprite: "insect1_eye",
            duration: 4388
        }, {
            sprite: "insect1_eggs",
            duration: 8035
        }, {
            sprite: "insect1_larva",
            duration: 11145
        }, {
            sprite: "insect1_climbing_adult",
            duration: 0
        }],
        insect2: [{
            sprite: "insect2_female_male",
            duration: 1543
        }, {
            sprite: "insect2_larva",
            duration: 25072
        }, {
            sprite: "insect2",
            duration: 0
        }],
        insect3: [{
            sprite: "insect3",
            duration: 23827
        }, {
            sprite: "insect3_sucker",
            duration: 16047
        }, {
            sprite: "insect3_clapping",
            duration: 6958
        }, {
            sprite: "insect3_eggs",
            duration: 4612
        }, {
            sprite: "insect3_larva",
            duration: 4249
        }, {
            sprite: "insect3_anotherspecies",
            duration: 0
        }],
        insect4: [{
            sprite: "insect4_water",
            duration: 13163
        }, {
            sprite: "insect4_legs",
            duration: 22570
        }, {
            sprite: "insect4",
            duration: 0
        }]
    },
    snails: {
        snail1: [{
            sprite: "snail1_leaf",
            duration: 35962
        }, {
            sprite: "snail1",
            duration: 23104
        }, {
            sprite: "snail1_conch",
            duration: 17778
        }, {
            sprite: "snail1",
            duration: 0
        }],
        snail2: [{
            sprite: "snail2_conch",
            duration: 11436
        }, {
            sprite: "snail2",
            duration: 12769
        }, {
            sprite: "snail2_leaf",
            duration: 0
        }],
        snail3: [{
            sprite: "snail3",
            duration: 4775
        }, {
            sprite: "snail3_anatomy",
            duration: 11961
        }, {
            sprite: "snail3_inunderwater",
            duration: 14306
        }, {
            sprite: "snail3_larva",
            duration: 14559
        }, {
            sprite: "snail3_evolution",
            duration: 0
        }]
    },
    frogevo: [{
        sprite: "fevo1",
        duration: 1500
    }, {
        sprite: "fevo2",
        duration: 1500
    }, {
        sprite: "fevo3",
        duration: 1500
    }, {
        sprite: "fevo4",
        duration: 1500
    }, {
        sprite: "fevo5",
        duration: 1500
    }, {
        sprite: "fevo6",
        duration: 1500
    }, {
        sprite: "fevo7",
        duration: 1500
    }, {
        sprite: "fevo8",
        duration: 1500
    }, {
        sprite: "fevo9",
        duration: 1500
    }, {
        sprite: "fevog1",
        duration: 1500
    }, {
        sprite: "fevog2",
        duration: 1500
    }, {
        sprite: "fevo9",
        duration: 1500
    }]
}